### ISSUE TITLE
App crashing on save - Windows

### ISSUE THREAD

**Issue by hallowf** [hallowf/STPDF#1]
The app on windows fails to save user settings, but this only seems to happen the second time the app is started and settings are saved

```
Traceback (most recent call last):
  File "components.py", line 200, in save_settings
  File "gui.py", line 615, in do_save
TypeError: 'NoneType' object is not iterable
```

**Comment by hallowf** [comment]
This bug is hard to reproduce and i'm still unsure how it is happening under certain circumstances.

The app is crashing on save due to `self.user_values` being `None` but the values are set as soon as the app starts loading, but this is only confirmed when save is called from the settings window, see [components.py](https://github.com/hallowf/STPDF/blob/dbcdb6a2ab660e34111e42456e2a90c7fdf8b58d/src/components.py#L189).

Is this possibly a race condition?

At the moment the current fix is 

```
uv = self.user_values
...
    if uv is not None:
        ...
```

But this isn't really a fix since the user values will still be None and the app will fail to save whoever it won't crash and warn the user in the console....
